### ISSUE TITLE
Post's table of contents not fully visible/accessible if window height not tall enough

### ISSUE THREAD

**Issue by joonas-fi** [stapelberg/hugo#8]
https://user-images.githubusercontent.com/630151/108479306-3be20700-729e-11eb-922b-c21cec05d0fa.mp4

It seems you can scroll to the TOC's bottom if you scroll to bottom of entire article. Sorry if this is by design, I don't know what I expected. Maybe an option would be to have a scroll-bar on the TOC if the toc is not entirely visible.

Setting `overflow-y: auto;` fixes this but not in a way I expected (bring scrollbar). Instead it makes the TOC reside at the top instead of being visible when you scroll the article.

(Apologies for the edits, as I accidentally pressed enter before I was ready..)

**Comment by stapelberg** [comment]
Thanks for the report, sorry I missed it for so long because it was in the wrong repository — I have now updated that repository with a pointer to this one and disabled issues over there.

The good news is that I think I have a fix: when setting `overflow-y: auto` as you suggested, we need to add `max-height: 100vh` to make the scrollbar appear.

This is now live, so give it a shot and let me know if something still doesn’t seem right :)
